version: '2'
exclude_patterns:
  # Raising similar-code check thresholds does not seem to work,
  # making spec files an enormous source of issues despite their
  # specific nature. As we can't tweak checks by file pattern,
  # we have no choice but to disable tests :-(
  #
  # Oddly enough, CodeClimate does auto-exclude tests, but hasn't
  # got the right pattern for JS to cover our `*.spec.js` files…
  - '**/*.spec.js'
  - '*.spec.js'
